#Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d6bm8j7pm1nc739n9q5g-a.singapore-postgres.render.com/moneymanager_22b0
spring.datasource.username=moneymanager_22b0_user
spring.datasource.password=YY1AjJB39yc8vZqg5A1JIUpDaX7AaEfL

